brace_style = "SameLineWhere"
combine_control_expr = false
control_brace_style = "ClosingNextLine"
edition = "2021"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
max_width = 155
normalize_doc_attributes = true
reorder_impl_items = true
tab_spaces = 2
use_field_init_shorthand = true
version = "Two"
